### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DRoce** [Quzile/Project-Zomboid-EtherHack#1] opened 2023-06-22 09:46 UTC
C:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid>java -jar ./EtherHack-0.0.1a.jar --install
[EtherHack]: Preparing to install the EtherHack...
[EtherHack]: Creating backup files...
[EtherHack]: Creating a backup file 'GameWindow.class' [1/3]
[EtherHack]: Creating a backup file 'core/Core.class' [2/3]
[EtherHack]: Creating a backup file 'network/GameServer.class' [3/3]
[EtherHack]: Preparation for implementation in game files...
[EtherHack]: Embedding a game window into a file
[EtherHack]: Embedding a game core into a file
[EtherHack]: Embedding a game network into a file
[EtherHack]: Unzipping EtherHack files...
[EtherHack]: An error occurred while unzipping EtherHack files: C:\Program%20Files%20(x86)\Steam\steamapps\common\ProjectZomboid\EtherHack-0.0.1a.jar (The system cannot find the path specified)
[EtherHack]: The cheat installation is complete, you can enter the game!

**Comment by DRoce** [comment] 2023-06-22 09:46
The game does not open, however it is in task manager

**Comment by Quzile** [comment] 2023-06-22 10:31
> C:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid>java -jar ./EtherHack-0.0.1a.jar --install [EtherHack]: Preparing to install the EtherHack... [EtherHack]: Creating backup files... [EtherHack]: Creating a backup file 'GameWindow.class' [1/3] [EtherHack]: Creating a backup file 'core/Core.class' [2/3] [EtherHack]: Creating a backup file 'network/GameServer.class' [3/3] [EtherHack]: Preparation for implementation in game files... [EtherHack]: Embedding a game window into a file [EtherHack]: Embedding a game core into a file [EtherHack]: Embedding a game network into a file [EtherHack]: Unzipping EtherHack files... [EtherHack]: An error occurred while unzipping EtherHack files: C:\Program%20Files%20(x86)\Steam\steamapps\common\ProjectZomboid\EtherHack-0.0.1a.jar (The system cannot find the path specified) [EtherHack]: The cheat installation is complete, you can enter the game!

The error is caused by an incorrect path to the JAR file. The file path contains percent signs (%), which Java interprets as URL-encoded characters. In this case, "%20" is a URL-encoded space. 

The bug has been fixed in version 0.0.2a. Try to remove the cheat and install a new version

**Closed** 2023-07-05 16:59 UTC
Labels: bug
